configfile: "config/config.yaml"

include: "rules/1_assembly.smk"
include: "rules/2_annotation.smk"
include: "rules/3_genome_level.smk"
include: "rules/4_homology_level.smk"
include: "rules/5_domain_level.smk"

rule all:
    input:
         #fastqc_before_trimming,
         "results/Genomics/1_Assembly/1_Preprocessing/fastqc_before_trimming",
        #ContaminationDetection.py
        #bwa_cleaning_contamination
         expand("/data/zeynep/HIN_data/DNA/clean/{reads}.fastq.gz",
           reads=config["reads"]),
         #trimmomatic
         expand("/data/zeynep/HIN_data/DNA/trimmed/paired/{sample}_R1.fastq",
                sample=["illumina_run1", "illumina_run2", "illumina_run3"]),
         #fastqc_after_trimming
         "results/Genomics/1_Assembly/1_Preprocessing/fastqc_after_trimming",
         ##flye
         expand("results/Genomics/1_Assembly/2_Assembly/flye/{process}",
                process=["clean", "raw"]),
         #masurca
        #"results/Genomics/1_Assembly/2_Assembly/masurca/flye.mr.33.17.15.0.02/",
         #bowtie_paired_reads_evaluation
         expand("results/Genomics/1_Assembly/3_Evaluation/{assembler}/bowtie2/paired/{sample}.bam",
                assembler=["flye/clean", "flye/raw", "masurca/flye.mr.33.17.15.0.02"],
                sample=["illumina_run1","illumina_run2", "illumina_run3"]),
        #bowtie_single_reads_evaluation
         expand("results/Genomics/1_Assembly/3_Evaluation/{assembler}/bowtie2/unpaired/{read}.bam",
                assembler=["flye/clean", "flye/raw", "masurca/flye.mr.33.17.15.0.02"],
                read=["illumina_run1_R1","illumina_run1_R2",
                        "illumina_run2_R1","illumina_run2_R2",
                        "illumina_run3_R1","illumina_run3_R2",]),
         #winnowmap evaluation
         expand("results/Genomics/1_Assembly/3_Evaluation/{assembler}/winnowmap/merlyDB",
                assembler=["flye/clean", "flye/raw", "masurca/flye.mr.33.17.15.0.02"],
                genome=["Hexamita"]),
         expand("results/Genomics/1_Assembly/3_Evaluation/{assembler}/winnowmap/repetitive_k15.txt",
                assembler=["flye/clean", "flye/raw", "masurca/flye.mr.33.17.15.0.02"],
                genome=["Hexamita"]),
         expand("results/Genomics/1_Assembly/3_Evaluation/{assembler}/winnowmap/{long_reads}.bam",
                assembler=["flye/clean", "flye/raw", "masurca/flye.mr.33.17.15.0.02"],
                long_reads=["nanopore", "pacbio"]),
         #pilon
         #expand("results/Genomics/1_Assembly/2_Assembly/pilon/{assembler}/assembly_polished.fasta",
           #     assembler=["flye/clean", "flye/raw", "masurca/flye.mr.33.17.15.0.02"]),
         #quast
         expand("results/Genomics/1_Assembly/3_Evaluation/quast/{assembler}/",
                assembler=["flye/clean", "flye/raw", "masurca/flye.mr.33.17.15.0.02"]),
        #deeptools
         expand("results/Genomics/1_Assembly/3_Evaluation/deeptools/{assembler}.png",
                assembler=["flye/clean", "flye/raw", "masurca/flye.mr.33.17.15.0.02"]),
         #multiqc
         expand("results/Genomics/1_Assembly/3_Evaluation/multiqc/{assembler}",
           assembler=["flye/clean", "flye/raw", "masurca/flye.mr.33.17.15.0.02"]),


    """
  #prodigal
         expand("results/Genomics/2_Annotation/1_Structural/{assembler}/prodigal/genome.gff",
                assembler=["flye", "masurca"]),
         #glimmerhmm
         expand("results/Genomics/2_Annotation/1_Structural/{assembler}/glimmerhmm/genome.faa",
                assembler=["flye", "masurca"]),
         #diamond_blastp
       #  expand("results/Genomics/2_Annotation/2_Functional/{assembler}/{annotation}/genome_diplomonads.blastp",
        #        annotation=["glimmerhmm"],
         #       assembler=["flye", "masurca"]),
         #eggnogmapper
         expand("results/Genomics/2_Annotation/2_Functional/{assembler}/{annotation}/eggnogmapper_results.tsv",
                annotation=["glimmerhmm"],
                assembler=["flye", "masurca"]),
         #interproscan
         expand("results/Genomics/2_Annotation/2_Functional/{assembler}/{annotation}/interproscan_results.tsv",
                annotation=["glimmerhmm"],
                assembler=["flye", "masurca"]),
        #repeatmodeler
         expand("results/ComparativeGenomics/1_GenomeStructureLevel/{assembler}/RModeler/genome_db-families.fasta",
                assembler=["flye", "masurca"]),
        #repeatmasker
            expand("results/ComparativeGenomics/1_GenomeStructureLevel/{assembler}/RMasker",
                   assembler=["flye", "masurca"]),
        #tRNAscan
            expand("results/Genomics/1_Assembly/2_Assembly/{assembler}/genome.tRNAscan",
                   assembler=["flye", "masurca"]),
        #tRNAscan_cov
            expand("results/Genomics/1_Assembly/2_Assembly/{assembler}/sensitive_search/genome.tRNAscan_cov",
                   assembler=["flye", "masurca"]),
        #barrnap
            expand("results/ComparativeGenomics/1_GenomeStructureLevel/{assembler}/genome.rrna.gff",
                   assembler=["flye", "masurca"]),
        #cdhit
            expand("results/ComparativeGenomics/1_GenomeStructureLevel/{assembler}/genome_{n}.cdhit",
                   assembler=["flye", "masurca"],
                   n=[0.70, 0.75, 0.80, 0.85, 0.90, 0.95, 1]),
        #orthofinder
            #"results/ComparativeGenomics/2_SequenceSimilarityLevel/"
        #orthofinder_rerun


#expand("results/2_cdhit/{sp}_{n}.cdhit", n=config["seq_identity"], sp=config["species"])
#expand("results/7_tRNAscan/{sp}.tRNAscan",sp=["HIN", "muris", "wb", "spiro"]),
#expand("results/7_tRNAscan/sensitive_search/{sp}.cov.tRNAscan",sp=[ "muris", "wb", "spiro"]),


Genomics Analysis
    1: Hybrid Genome Assembly Workflow 
        -Reads Preprocessing
        -Assembly
        -Evaluation
    2: Genome Annotation Workflow
        -Structural Annotation
        -Functional Annotation
"""
